/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xxl_core_io_raw_NativeRawAccess */

#ifndef _Included_xxl_core_io_raw_NativeRawAccess
#define _Included_xxl_core_io_raw_NativeRawAccess
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     xxl_core_io_raw_NativeRawAccess
 * Method:    open
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_xxl_core_io_raw_NativeRawAccess_open
  (JNIEnv *, jobject, jstring);

/*
 * Class:     xxl_core_io_raw_NativeRawAccess
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_xxl_core_io_raw_NativeRawAccess_close
  (JNIEnv *, jobject);

/*
 * Class:     xxl_core_io_raw_NativeRawAccess
 * Method:    write
 * Signature: ([BJ)V
 */
JNIEXPORT void JNICALL Java_xxl_core_io_raw_NativeRawAccess_write
  (JNIEnv *, jobject, jbyteArray, jlong);

/*
 * Class:     xxl_core_io_raw_NativeRawAccess
 * Method:    read
 * Signature: ([BJ)V
 */
JNIEXPORT void JNICALL Java_xxl_core_io_raw_NativeRawAccess_read
  (JNIEnv *, jobject, jbyteArray, jlong);

#ifdef __cplusplus
}
#endif
#endif
